import { useEffect, useState } from "react";
import api from "../../lib/api";
import { cachedGet, cacheRemove } from "../../lib/cache";
import RefreshButton from "../../components/RefreshButton";

const featureList=["catalog","pos","customers","inventory","purchases","suppliers","reports","expenses","staff","sizes","collections","online_orders","notifications","campaigns","loyalty","domains","pwa","seo","advanced_analytics"];
export default function Tenants(){
 const [rows,setRows]=useState([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[plans,setPlans]=useState([]),[busy,setBusy]=useState(""),[selected,setSelected]=useState(null),[form,setForm]=useState(null);
 const [registerOpen,setRegisterOpen]=useState(false);
 const [registerForm,setRegisterForm]=useState({shopName:"",slug:"",username:"",password:"",plan:""});
 const [registerError,setRegisterError]=useState("");
 async function load(force=false){const query=`/super-admin/tenants?q=${encodeURIComponent(q)}&status=${encodeURIComponent(status)}`;const r=await cachedGet(api,query,{key:`platform:tenants:${q}:${status}`,forceRefresh:force,revalidate:true,scope:"global"});setRows(r.data.tenants||[]);}
 useEffect(()=>{load();cachedGet(api,"/super-admin/plans",{key:"platform:plans",revalidate:true,scope:"global"}).then(r=>setPlans(r.data.plans||[]));},[status]);
 async function statusChange(id,value){setBusy(id);try{await api.patch(`/super-admin/tenants/${id}/status`,{status:value});await load()}finally{setBusy("")}}
 async function planChange(id,value){setBusy(id);try{await api.patch(`/super-admin/tenants/${id}/plan`,{plan:value});await load()}finally{setBusy("")}}
 function openManage(t){const ov=t.featureOverrides||{enabled:[],disabled:[]};setSelected(t);setForm({enabled:ov.enabled||[],disabled:ov.disabled||[],billingCycle:t.subscription?.billingCycle||"monthly",startedAt:t.subscription?.startedAt?t.subscription.startedAt.slice(0,10):"",currentPeriodEnd:t.subscription?.currentPeriodEnd?t.subscription.currentPeriodEnd.slice(0,10):"",devEnabled:t.developerBranding?.enabled!==false,devName:t.developerBranding?.name||"Noorie Collection Developers",devText:t.developerBranding?.text||"Powered by our fashion commerce platform.",devWebsite:t.developerBranding?.website||"",devEmail:t.developerBranding?.email||"",devWhatsapp:t.developerBranding?.whatsapp||""})}
 function toggle(key,f){setForm(v=>{const other=key==="enabled"?"disabled":"enabled"; const next=v[key].includes(f)?v[key].filter(x=>x!==f):[...v[key],f]; return {...v,[key]:next,[other]:v[other].filter(x=>x!==f)}})}
 async function save(){if(!selected||!form)return;setBusy("manage");try{await api.patch(`/super-admin/tenants/${selected.id}/features`,{enabled:form.enabled,disabled:form.disabled});await api.patch(`/super-admin/tenants/${selected.id}/subscription`,{billingCycle:form.billingCycle,startedAt:form.startedAt,currentPeriodEnd:form.currentPeriodEnd,planCode:selected.plan});await api.patch(`/super-admin/tenants/${selected.id}/developer-branding`,{enabled:form.devEnabled,name:form.devName,text:form.devText,website:form.devWebsite,email:form.devEmail,whatsapp:form.devWhatsapp});await load();setSelected(null);setForm(null)}finally{setBusy("")}}

 async function registerShop(e){
   e.preventDefault(); setRegisterError(""); setBusy("register");
   try{
     const r=await api.post("/super-admin/tenants",registerForm);
     setRegisterOpen(false);
     setRegisterForm({shopName:"",slug:"",username:"",password:"",plan:plans[0]?.code||""});
     await load(true);
     alert(r.data?.message || "Shop registered successfully.");
   }catch(err){setRegisterError(err.response?.data?.message || "Could not register shop.");}
   finally{setBusy("");}
 }

 return <div><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Tenants</h1><p className="mt-1 text-slate-500">Manage stores, plans, access, subscriptions and developer branding.</p></div><div className="flex gap-2"><RefreshButton onClick={()=>load(true)} busy={busy==="refresh"}/><button className="btn-primary" onClick={()=>{setRegisterError("");setRegisterOpen(true)}}>Register Shop</button></div></div>
 <div className="mt-6 card p-4 flex flex-wrap gap-3"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="Search store or slug" className="rounded-2xl bg-slate-100 p-3 flex-1 min-w-56"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-2xl bg-slate-100 p-3"><option value="">All status</option><option value="trial">Trial</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="cancelled">Cancelled</option></select><button className="btn-primary" onClick={load}>Search</button></div>
 <div className="mt-5 grid gap-4">{rows.map(t=><div className="card p-5" key={t.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-black">{t.name}</h2><p className="text-sm text-slate-500">/{t.slug} · owner: {t.owner?.username||"—"}</p><div className="mt-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-slate-100 px-3 py-1">{t.status}</span><span className="rounded-full bg-slate-100 px-3 py-1">{t.plan}</span><span className="rounded-full bg-slate-100 px-3 py-1">{t.counts.products} products</span><span className="rounded-full bg-slate-100 px-3 py-1">{t.counts.customers} customers</span><span className="rounded-full bg-slate-100 px-3 py-1">{t.counts.orders} orders</span></div></div><div className="flex flex-wrap gap-2"><select disabled={busy===t.id} value={t.plan} onChange={e=>planChange(t.id,e.target.value)} className="rounded-xl bg-slate-100 p-2">{plans.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</select><select disabled={busy===t.id} value={t.status} onChange={e=>statusChange(t.id,e.target.value)} className="rounded-xl bg-slate-100 p-2"><option value="trial">Trial</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="cancelled">Cancelled</option></select><button className="btn-soft" onClick={()=>openManage(t)}>Manage access</button></div></div></div>)}</div>
 {!rows.length&&<div className="mt-6 card p-8 text-center text-slate-500">No tenants found.</div>}
 {selected&&form&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={()=>setSelected(null)}><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-3xl bg-white p-5 sm:p-7" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><h2 className="text-2xl font-black">Manage {selected.name}</h2><p className="text-sm text-slate-500">Plan features, tenant overrides, subscription dates and developer details.</p></div><button className="btn-soft" onClick={()=>setSelected(null)}>Close</button></div>
 <section className="mt-6"><h3 className="font-black">Feature access</h3><p className="mt-1 text-xs text-slate-500">Enabled overrides add a feature. Disabled overrides remove it even when the plan includes it.</p><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{featureList.map(f=><div key={f} className="rounded-2xl border p-3"><div className="font-bold capitalize">{f.replaceAll("_"," ")}</div><div className="mt-2 flex gap-2 text-xs"><button type="button" className={`rounded-xl px-3 py-2 font-bold ${form.enabled.includes(f)?"bg-emerald-100 text-emerald-800":"bg-slate-100"}`} onClick={()=>toggle("enabled",f)}>Allow</button><button type="button" className={`rounded-xl px-3 py-2 font-bold ${form.disabled.includes(f)?"bg-rose-100 text-rose-800":"bg-slate-100"}`} onClick={()=>toggle("disabled",f)}>Disallow</button></div></div>)}</div></section>
 <section className="mt-6"><h3 className="font-black">Manual subscription</h3><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm font-bold">Billing cycle<select className="input mt-1" value={form.billingCycle} onChange={e=>setForm(v=>({...v,billingCycle:e.target.value}))}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label className="text-sm font-bold">Start date<input type="date" className="input mt-1" value={form.startedAt} onChange={e=>setForm(v=>({...v,startedAt:e.target.value}))}/></label><label className="text-sm font-bold">End date<input type="date" className="input mt-1" value={form.currentPeriodEnd} onChange={e=>setForm(v=>({...v,currentPeriodEnd:e.target.value}))}/></label></div></section>
 <section className="mt-6"><h3 className="font-black">Developer details shown on public shop</h3><label className="mt-2 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.devEnabled} onChange={e=>setForm(v=>({...v,devEnabled:e.target.checked}))}/> Show developer credit</label><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className="input" placeholder="Developer name" value={form.devName} onChange={e=>setForm(v=>({...v,devName:e.target.value}))}/><input className="input" placeholder="Developer website" value={form.devWebsite} onChange={e=>setForm(v=>({...v,devWebsite:e.target.value}))}/><input className="input" placeholder="Developer email" value={form.devEmail} onChange={e=>setForm(v=>({...v,devEmail:e.target.value}))}/><input className="input" placeholder="Developer WhatsApp" value={form.devWhatsapp} onChange={e=>setForm(v=>({...v,devWhatsapp:e.target.value}))}/><textarea className="input sm:col-span-2" placeholder="Developer credit text" value={form.devText} onChange={e=>setForm(v=>({...v,devText:e.target.value}))}/></div></section>
 <div className="mt-6 flex justify-end gap-2"><button className="btn-soft" onClick={()=>setSelected(null)}>Cancel</button><button className="btn-primary" disabled={busy==="manage"} onClick={save}>{busy==="manage"?"Saving...":"Save changes"}</button></div></div></div>}
 {registerOpen&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={()=>setRegisterOpen(false)}><form className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl" onClick={e=>e.stopPropagation()} onSubmit={registerShop}><h2 className="text-2xl font-black">Register Shop</h2><p className="mt-1 text-sm text-slate-500">Platform Admin creates the store directly as active. No trial is created.</p>{registerError&&<div className="mt-4 rounded-2xl bg-red-50 p-3 text-sm font-semibold text-red-700">{registerError}</div>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Shop name<input required className="input mt-1" value={registerForm.shopName} onChange={e=>setRegisterForm(v=>({...v,shopName:e.target.value}))}/></label><label className="text-sm font-bold">Shop slug<input className="input mt-1" value={registerForm.slug} onChange={e=>setRegisterForm(v=>({...v,slug:e.target.value.toLowerCase()}))} placeholder="auto-generated"/></label><label className="text-sm font-bold">Owner username<input required className="input mt-1" value={registerForm.username} onChange={e=>setRegisterForm(v=>({...v,username:e.target.value.toLowerCase()}))}/></label><label className="text-sm font-bold">Owner password<input required type="password" className="input mt-1" value={registerForm.password} onChange={e=>setRegisterForm(v=>({...v,password:e.target.value}))}/></label><label className="text-sm font-bold sm:col-span-2">Plan<select required className="input mt-1" value={registerForm.plan} onChange={e=>setRegisterForm(v=>({...v,plan:e.target.value}))}><option value="">Select active plan</option>{plans.filter(p=>p.active!==false).map(p=><option key={p.code} value={p.code}>{p.name} · ₹{p.monthlyPrice}/month</option>)}</select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-soft" onClick={()=>setRegisterOpen(false)}>Cancel</button><button className="btn-primary" disabled={busy==="register"}>{busy==="register"?"Registering...":"Register Shop"}</button></div></form></div>}
 </div>
}
