import { useEffect, useState } from "react";
import { ArrowRight, Search } from "lucide-react";
import api from "../../lib/api";
import Pagination from "../../components/Pagination";
import { money } from "../../lib/utils";
import { showAlert } from "../../lib/feedback";

export default function Bookings(){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[status,setStatus]=useState("active"),[page,setPage]=useState(1),[pagination,setPagination]=useState({pages:1,total:0}),[loading,setLoading]=useState(false);
 async function load(){setLoading(true);try{const r=await api.get("/bookings/admin/list",{params:{q,status,page,limit:20}});setItems(r.data?.items||[]);setPagination(r.data?.pagination||{pages:1,total:0});}catch(e){showAlert(e.response?.data?.message||"Unable to load bookings.")}finally{setLoading(false)}}
 useEffect(()=>{setPage(1)},[q,status]); useEffect(()=>{load()},[q,status,page]);
 async function convert(id){try{await api.post(`/bookings/admin/${id}/convert`);await load();showAlert("Booking converted to an online order.","Converted")}catch(e){showAlert(e.response?.data?.message||"Could not convert booking.")}}
 return <div className="mx-auto max-w-7xl"><h1 className="text-3xl font-black">Booked Items</h1><p className="mt-1 text-sm text-slate-500">Items reserved for store visits. Reservations expire automatically after 24 hours if the customer does not respond.</p>
 <div className="mt-6 grid gap-3 md:grid-cols-[1fr_220px]"><div className="card relative p-3"><Search className="absolute left-6 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="input w-full pl-10" value={q} onChange={e=>setQ(e.target.value)} placeholder="Booking ID, customer, phone, product..."/></div><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All</option>{["active","converted","expired","released","cancelled"].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="card mt-5 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Booking</th><th className="p-4">Item</th><th className="p-4">Customer</th><th className="p-4">Qty</th><th className="p-4">Value</th><th className="p-4">Expires</th><th className="p-4"></th></tr></thead><tbody>{items.map(b=><tr key={b.id} className="border-t"><td className="p-4 font-black">{b.bookingNumber}<div className="text-xs font-semibold capitalize text-slate-500">{b.status}</div></td><td className="p-4">{b.productName}<div className="text-xs text-slate-500">{[b.size,b.color].filter(Boolean).join(" / ")||b.sku}</div></td><td className="p-4">{b.customerName}<div className="text-xs text-slate-500">{b.customerPhone}</div></td><td className="p-4">{b.quantity}</td><td className="p-4 font-black">{money(b.unitPrice*b.quantity)}</td><td className="p-4 text-slate-500">{new Date(b.expiresAt).toLocaleString()}</td><td className="p-4">{b.status==="active"&&<button className="btn-primary" onClick={()=>convert(b.id)}>Make Online Order <ArrowRight size={16}/></button>}</td></tr>)}</tbody></table></div>{!loading&&!items.length&&<div className="p-10 text-center text-sm text-slate-400">No bookings found.</div>}</div><Pagination page={page} pages={pagination.pages||1} total={pagination.total||0} onChange={setPage}/></div>
}
