import { useEffect, useState } from "react";
import { Eye, Search, Truck, MessageCircle, Copy, ExternalLink } from "lucide-react";
import api from "../../lib/api";
import { money } from "../../lib/utils";
import { Link } from "react-router-dom";
import Pagination from "../../components/Pagination";

const STATUSES=["pending","confirmed","processing","packed","shipped","out_for_delivery","delivered","cancelled"];
function whatsappOrderUrl(order) {
 const digits=String(order?.contact?.whatsapp||order?.customerPhone||"").replace(/\D/g,"");
 if(!digits) return "#";
 const t=order?.deliveryTracking?.trackingId||"";
 const msg=t ? `Hello ${order.customerName}, your ${order.orderNumber} payment is confirmed. Courier tracking ID: ${t}${order.deliveryTracking?.trackingUrl ? `\nTrack: ${order.deliveryTracking.trackingUrl}` : ""}` : `Hello ${order.customerName}, your ${order.orderNumber} payment is confirmed. We will update you when courier tracking is available.`;
 return `https://wa.me/${digits}?text=${encodeURIComponent(msg)}`;
}

export default function OnlineOrders(){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[status,setStatus]=useState(""),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false);
 const [page,setPage]=useState(1),[pagination,setPagination]=useState({pages:1,total:0}),[allDates,setAllDates]=useState(false);
 const [draft,setDraft]=useState({fulfillmentStatus:"pending",trackingId:"",courierName:"",trackingUrl:"",adminNote:""});
 async function load(){setLoading(true);try{const r=await api.get("/orders/online/list",{params:{page,limit:20,q,status,all:allDates?1:0}});setItems(r.data?.items||[]);setPagination(r.data?.pagination||{pages:1,total:0});}catch(e){console.error(e)}finally{setLoading(false)}}
 useEffect(()=>{setPage(1)},[q,status,allDates]); useEffect(()=>{load()},[q,status,page,allDates]);
 function open(o){setSelected(o);setDraft({fulfillmentStatus:o.fulfillmentStatus||"pending",trackingId:o.deliveryTracking?.trackingId||"",courierName:o.deliveryTracking?.courierName||"",trackingUrl:o.deliveryTracking?.trackingUrl||"",adminNote:""})}
 async function save(){try{const r=await api.patch(`/orders/online/${selected._id}`,draft);setSelected(r.data);await load()}catch(e){console.error(e)}}
 return <div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Online Orders</h1><p className="mt-1 text-sm text-slate-500">Website orders with customer, delivery, stock and courier tracking details.</p></div><Link to="/admin/online-orders/new" className="btn-primary">Create Online Order</Link></div>
 <div className="mt-6 grid gap-3 md:grid-cols-[1fr_220px_auto]"><div className="card relative p-3"><Search className="absolute left-6 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="w-full rounded-2xl bg-slate-100 py-3 pl-10 pr-4" placeholder="Order ID, customer, phone or tracking ID..." value={q} onChange={e=>setQ(e.target.value)}/></div><select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{STATUSES.map(s=><option key={s}>{s.replaceAll("_"," ")}</option>)}</select><label className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 text-sm font-bold shadow-sm"><input type="checkbox" checked={allDates} onChange={e=>setAllDates(e.target.checked)}/> Fetch older</label></div>
 <div className="mt-5 card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Order</th><th className="p-4">Customer</th><th className="p-4">Items</th><th className="p-4">Payment</th><th className="p-4">Delivery</th><th className="p-4">Total</th><th className="p-4">Date</th><th className="p-4"></th></tr></thead><tbody>{items.map(o=><tr key={o._id} className="border-t"><td className="p-4 font-black">{o.orderNumber}<div className="mt-1 text-xs font-semibold capitalize text-slate-500">{o.fulfillmentStatus?.replaceAll("_"," ")}</div></td><td className="p-4">{o.customerName}<div className="text-xs text-slate-500">{o.customerPhone}</div><div className="text-xs text-slate-500">{o.contact?.email}</div></td><td className="p-4">{o.items?.reduce((n,i)=>n+i.quantity,0)} items</td><td className="p-4">{o.paymentMethod}<div className="text-xs text-amber-700">{o.paymentStatus}</div></td><td className="p-4">{o.delivery?.city}, {o.delivery?.state}<div className="text-xs text-slate-500">{o.delivery?.postalCode}</div></td><td className="p-4 font-black">{money(o.finalTotal)}</td><td className="p-4 text-slate-500">{new Date(o.createdAt).toLocaleString()}</td><td className="p-4"><button className="btn-soft" onClick={()=>open(o)}><Eye size={16}/> Manage</button></td></tr>)}</tbody></table></div>{!loading&&!items.length&&<div className="p-10 text-center text-sm text-slate-400">No online orders found.</div>}</div>
 <Pagination page={page} pages={pagination.pages||1} total={pagination.total||0} onChange={setPage}/>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={()=>setSelected(null)}><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white p-5 sm:p-6" onClick={e=>e.stopPropagation()}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase font-bold text-slate-400">Online Order</p><h2 className="text-2xl font-black">{selected.orderNumber}</h2><p className="text-sm text-slate-500">{selected.customerName} · {selected.customerPhone}</p></div><button className="btn-soft" onClick={()=>setSelected(null)}>Close</button></div>
 <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><div className="font-black">Customer</div><p className="mt-2 text-sm">{selected.customerName}<br/>{selected.customerPhone}<br/>{selected.contact?.email||"No email"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><div className="font-black">Delivery Address</div><p className="mt-2 text-sm">{[selected.delivery?.addressLine1,selected.delivery?.addressLine2,selected.delivery?.landmark,selected.delivery?.city,selected.delivery?.state,selected.delivery?.postalCode,selected.delivery?.country].filter(Boolean).join(", ")}</p>{selected.delivery?.instructions&&<p className="mt-2 text-xs text-slate-500">Note: {selected.delivery.instructions}</p>}</div></div>
 <div className="mt-5 space-y-2">{selected.items?.map((i,n)=><div key={n} className="flex justify-between rounded-2xl border p-3"><div><b>{i.name}</b><div className="text-xs text-slate-500">{[i.size,i.color].filter(Boolean).join(" / ")||i.sku} · Qty {i.quantity}</div></div><b>{money(i.lineTotal)}</b></div>)}</div>
 <div className="mt-5 grid gap-3 sm:grid-cols-2">{selected.deliveryTracking?.trackingId?<div className="rounded-2xl bg-emerald-50 p-4 text-sm"><b>Courier tracking is active</b><p className="mt-1">Tracking ID: {selected.deliveryTracking.trackingId}</p><p className="text-slate-600">Status is driven by courier tracking; manual status changes are locked.</p></div>:<label className="text-sm font-bold">Order status<select className="input mt-1" value={draft.fulfillmentStatus} onChange={e=>setDraft(v=>({...v,fulfillmentStatus:e.target.value}))}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label>}<label className="text-sm font-bold">Tracking ID<input className="input mt-1" value={draft.trackingId} onChange={e=>setDraft(v=>({...v,trackingId:e.target.value}))} placeholder="Courier tracking ID"/></label><label className="text-sm font-bold">Courier<input className="input mt-1" value={draft.courierName} onChange={e=>setDraft(v=>({...v,courierName:e.target.value}))}/></label><label className="text-sm font-bold">Tracking URL<input className="input mt-1" value={draft.trackingUrl} onChange={e=>setDraft(v=>({...v,trackingUrl:e.target.value}))} placeholder="https://..."/></label></div>
 <textarea className="input mt-3 min-h-20" value={draft.adminNote} onChange={e=>setDraft(v=>({...v,adminNote:e.target.value}))} placeholder="Internal order note"/>
 <div className="mt-5 flex flex-wrap justify-between gap-3"><div><div className="text-xl font-black">{money(selected.finalTotal)}</div><div className="text-xs text-slate-500">Payment status: {selected.paymentStatus}</div></div><div className="flex flex-wrap gap-2">{selected.deliveryTracking?.trackingId && <><button className="btn-soft" type="button" onClick={()=>navigator.clipboard?.writeText(selected.deliveryTracking.trackingId)}><Copy size={16}/> Copy Tracking ID</button>{selected.paymentStatus === "paid" && <a className="btn-soft" href={whatsappOrderUrl(selected)} target="_blank" rel="noreferrer"><MessageCircle size={16}/> WhatsApp Customer</a>}{selected.deliveryTracking?.trackingUrl && <a className="btn-soft" href={selected.deliveryTracking.trackingUrl} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Courier</a>}</>}<button className="btn-soft text-rose-700" type="button" onClick={()=>{setDraft(v=>({...v,fulfillmentStatus:"cancelled"}));setTimeout(save,0)}}>Cancel & Reverse</button><button className="btn-primary" onClick={save}><Truck size={17}/> Save Tracking</button></div></div><p className="mt-4 rounded-2xl bg-rose-50 p-3 text-xs text-slate-600">Online orders cannot be returned online. Customer can visit the store for assistance.</p><p className="mt-2 rounded-2xl bg-blue-50 p-3 text-xs font-semibold text-blue-900">After payment is confirmed, copy the Tracking ID and use WhatsApp Customer to send the tracking code and courier link.</p></div></div>}</div>
}
