import { useEffect, useMemo, useState } from "react";
import { BarChart3, IndianRupee, ShoppingCart, RotateCcw, TrendingUp, Package, Users, RefreshCw, Percent, Palette, Ruler, Boxes, AlertTriangle } from "lucide-react";
import api from "../../lib/api";
import { money } from "../../lib/utils";

function iso(d){ return d.toISOString().slice(0,10); }
function defaultDates(){ const end=new Date(); const start=new Date(); start.setDate(end.getDate()-29); return {start:iso(start),end:iso(end)}; }
function pct(v){ return `${Number(v||0).toFixed(1)}%`; }

export default function Reports(){
  const [dates,setDates]=useState(defaultDates);
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  async function load(){ setLoading(true);setError(""); try{ const r=await api.get("/reports/overview",{params:dates});setData(r.data); }catch(e){setError(e.response?.data?.message||"Unable to load reports.");}finally{setLoading(false);} }
  useEffect(()=>{load();},[]);
  const maxDaily=useMemo(()=>Math.max(1,...(data?.daily||[]).map(x=>Number(x.sales)||0)),[data]);
  const maxProduct=useMemo(()=>Math.max(1,...(data?.topProducts||[]).map(x=>Number(x.sales)||0)),[data]);
  const summary=data?.summary||{}, inventory=data?.inventory||{}, comparison=data?.comparison||{}, customers=data?.customerMetrics||{};
  const quick=[
    ["Net Revenue",money(summary.netRevenue),IndianRupee], ["Net Profit",money(summary.netProfit),TrendingUp],
    ["Orders",summary.orders,ShoppingCart], ["Average Order Value",money(summary.averageOrderValue),IndianRupee],
    ["Repeat Customer Rate",pct(summary.repeatCustomerRate),Percent], ["New Customers",summary.newCustomers,Users],
    ["Returns",money(summary.returnedAmount),RotateCcw], ["Expenses",money(summary.expenses),IndianRupee]
  ];
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Reports & Business Intelligence</h1><p className="mt-1 text-slate-500">Compare performance, understand customers and find inventory opportunities.</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-sm font-semibold">From<input type="date" value={dates.start} onChange={e=>setDates(x=>({...x,start:e.target.value}))} className="input mt-1"/></label><label className="text-sm font-semibold">To<input type="date" value={dates.end} onChange={e=>setDates(x=>({...x,end:e.target.value}))} className="input mt-1"/></label><button className="btn-soft" onClick={load} disabled={loading}><RefreshCw size={16} className={loading?"animate-spin":""}/> {loading?"Loading":"Apply"}</button></div></div>
    {error&&<div className="mt-5 rounded-2xl bg-red-50 p-4 text-red-700">{error}</div>}
    {data&&<>
      <div className="mt-7 grid grid-cols-2 gap-4 lg:grid-cols-4">{quick.map(([label,value,Icon])=><div className="card p-5" key={label}><Icon size={20}/><div className="mt-3 text-2xl font-black">{value}</div><div className="text-sm text-slate-500">{label}</div></div>)}</div>
      <div className="mt-5 grid gap-4 lg:grid-cols-3"><div className="card p-6"><div className="text-sm text-slate-500">Revenue vs previous period</div><div className="mt-2 text-3xl font-black">{pct(comparison.revenueChangePct)}</div><div className="mt-1 text-xs text-slate-500">Previous: {money(comparison.previousRevenue)}</div></div><div className="card p-6"><div className="text-sm text-slate-500">Orders vs previous period</div><div className="mt-2 text-3xl font-black">{pct(comparison.ordersChangePct)}</div><div className="mt-1 text-xs text-slate-500">Previous: {comparison.previousOrders||0}</div></div><div className="card p-6"><div className="text-sm text-slate-500">Profit vs previous period</div><div className="mt-2 text-3xl font-black">{pct(comparison.profitChangePct)}</div><div className="mt-1 text-xs text-slate-500">Previous: {money(comparison.previousProfit)}</div></div></div>
      <div className="mt-6 grid gap-5 lg:grid-cols-3"><div className="card p-6 lg:col-span-2"><h2 className="font-black">Daily sales trend</h2><div className="mt-5 flex h-56 items-end gap-1 overflow-x-auto">{data.daily.map(x=><div key={x.date} className="flex min-w-[24px] flex-1 flex-col items-center justify-end gap-1" title={`${x.date}: ${money(x.sales)}`}><div className="w-full rounded-t-lg bg-amber-300" style={{height:`${Math.max(3,(x.sales/maxDaily)*100)}%`}}></div><span className="text-[9px] text-slate-400">{x.date.slice(5)}</span></div>)}</div></div><div className="card p-6"><h2 className="font-black">Payment methods</h2><div className="mt-4 space-y-3">{data.payments.length?data.payments.map(x=><div key={x.method} className="flex justify-between gap-3"><span>{x.method}</span><b>{money(x.amount)}</b></div>):<p className="text-sm text-slate-500">No sales in this period.</p>}</div></div></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="font-black">Top products</h2><div className="mt-4 space-y-4">{data.topProducts.map(x=><div key={`${x.productId}-${x.sku}`}><div className="flex justify-between gap-3 text-sm"><span className="font-semibold">{x.name} <span className="text-slate-400">({x.sku})</span></span><b>{money(x.sales)}</b></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-amber-300" style={{width:`${Math.max(2,(x.sales/maxProduct)*100)}%`}}/></div><div className="mt-1 text-xs text-slate-500">{x.quantity} units · Profit {money(x.profit)}</div></div>)}</div>{!data.topProducts.length&&<p className="mt-4 text-sm text-slate-500">No product sales in this period.</p>}</div><div className="card p-6"><h2 className="font-black">Top categories</h2><div className="mt-4 space-y-3">{data.topCategories.map(x=><div className="flex items-center justify-between rounded-xl bg-slate-50 p-3" key={x.categoryId||x.name}><span>{x.name}</span><span className="text-right"><b>{money(x.sales)}</b><small className="ml-2 text-slate-500">{x.quantity} units</small></span></div>)}</div></div></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="flex items-center gap-2 font-black"><Ruler size={18}/> Best-selling sizes</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{data.topSizes.map(x=><div className="rounded-2xl bg-slate-50 p-4" key={x.size}><div className="font-black">{x.size}</div><div className="text-sm text-slate-500">{x.quantity} units</div><div className="text-xs">{money(x.sales)}</div></div>)}</div>{!data.topSizes.length&&<p className="mt-4 text-sm text-slate-500">No size-level sales data.</p>}</div><div className="card p-6"><h2 className="flex items-center gap-2 font-black"><Palette size={18}/> Best-selling colors</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5">{data.topColors.map(x=><div className="rounded-2xl bg-slate-50 p-4" key={x.color}><div className="truncate font-black">{x.color}</div><div className="text-sm text-slate-500">{x.quantity} units</div><div className="text-xs">{money(x.sales)}</div></div>)}</div>{!data.topColors.length&&<p className="mt-4 text-sm text-slate-500">No color-level sales data.</p>}</div></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-3"><div className="card p-6 lg:col-span-2"><h2 className="font-black">Customer intelligence</h2><div className="mt-4 grid grid-cols-2 gap-4 md:grid-cols-4"><div><div className="text-xs text-slate-500">Total customers</div><b className="text-xl">{customers.totalCustomers||0}</b></div><div><div className="text-xs text-slate-500">Repeat customers</div><b className="text-xl">{customers.repeatCustomers||0}</b></div><div><div className="text-xs text-slate-500">Repeat rate</div><b className="text-xl">{pct(customers.repeatCustomerRate)}</b></div><div><div className="text-xs text-slate-500">Avg lifetime spend</div><b className="text-xl">{money(customers.averageLifetimeSpend)}</b></div></div></div><div className="card p-6"><h2 className="font-black">Inventory valuation</h2><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between"><span>Units</span><b>{inventory.units||0}</b></div><div className="flex justify-between"><span>Cost value</span><b>{money(inventory.costValue)}</b></div><div className="flex justify-between"><span>Retail value</span><b>{money(inventory.retailValue)}</b></div><div className="flex justify-between"><span>Potential profit</span><b>{money(inventory.potentialProfit)}</b></div></div></div></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="card p-6"><h2 className="flex items-center gap-2 font-black"><AlertTriangle size={18}/> Dead-stock candidates</h2><p className="mt-1 text-xs text-slate-500">In-stock products created at least 60 days before the selected period and with no recorded sale during it.</p><div className="mt-4 space-y-2">{data.deadStock.map(x=><div className="flex justify-between rounded-xl bg-slate-50 p-3" key={x._id}><span>{x.name}<small className="ml-2 text-slate-400">{x.sku}</small></span><b>{x.stockQuantity}</b></div>)}</div>{!data.deadStock.length&&<p className="mt-4 text-sm text-slate-500">No candidates found.</p>}</div><div className="card p-6"><h2 className="flex items-center gap-2 font-black"><Boxes size={18}/> Low stock</h2><div className="mt-4 grid gap-2 md:grid-cols-2">{data.lowStock.map(x=><div className="flex justify-between rounded-xl bg-slate-50 p-3" key={x._id}><span>{x.name}<small className="ml-2 text-slate-400">{x.sku}</small></span><b>{x.stockQuantity}</b></div>)}</div>{!data.lowStock.length&&<p className="mt-4 text-sm text-slate-500">No low-stock products found.</p>}</div></div>
    </>}
  </div>;
}
