import {useEffect,useState} from "react";
import api from "../../lib/api";
import { cachedGet } from "../../lib/cache";
import {useAuth} from "../../context/AuthContext";

const labels={manager:"Manager",sales:"Sales",inventory:"Inventory",staff:"Staff"};
const groups={
 Core:["dashboard.view","products.view","products.create","products.edit","products.delete","sales.view","sales.create","customers.view","customers.create","customers.edit"],
 Operations:["suppliers.view","suppliers.create","suppliers.edit","purchases.view","purchases.create","inventory.view","inventory.adjust","returns.view","returns.create"],
 Storefront:["categories.view","categories.create","categories.edit","collections.view","collections.create","collections.edit","collections.delete","settings.view","settings.edit","domains.view","domains.manage"],
 Engagement:["notifications.view","notifications.create","campaigns.view","campaigns.manage","loyalty.view","loyalty.manage"],
 Reporting:["reports.view","expenses.view","expenses.manage","audit.view","usage.view","billing.view","staff.view","staff.manage"]
};
export default function Staff(){
 const {admin}=useAuth(); const [rows,setRows]=useState([]); const [roles,setRoles]=useState([]); const [rolePermissions,setRolePermissions]=useState({}); const [loading,setLoading]=useState(true); const [editing,setEditing]=useState(null);
 const [form,setForm]=useState({username:"",password:"",role:"sales",permissions:[]}); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 const canManage=admin?.role==="owner"||admin?.role==="super_admin"||admin?.permissions?.includes("staff.manage");
 const load=()=>Promise.all([cachedGet(api,"/staff",{key:"staff:admin"}),cachedGet(api,"/staff/roles",{key:"staff:roles"})]).then(([a,b])=>{setRows(a.data.staff||a.data?.data?.staff||[]);setRoles(b.data.roles||b.data?.data?.roles||[]);setRolePermissions(b.data.rolePermissions||{})}).finally(()=>setLoading(false));
 useEffect(()=>{load().catch(e=>setError(e.response?.data?.message||"Unable to load staff."))},[]);
 const create=async e=>{e.preventDefault();setError("");setSaving(true);try{await api.post("/staff",form);setForm({username:"",password:"",role:"sales",permissions:[]});await load()}catch(e){setError(e.response?.data?.message||"Unable to create staff.")}finally{setSaving(false)}};
 const toggle=async row=>{try{await api.put(`/staff/${row.id}`,{active:!row.active});await load()}catch(e){setError(e.response?.data?.message||"Unable to update staff.")}};
 const startEdit=row=>{setEditing(row.id);setForm({username:row.username,password:"",role:row.role,permissions:row.permissions||[]})};
 const saveEdit=async e=>{e.preventDefault();setSaving(true);try{await api.put(`/staff/${editing}`,form);setEditing(null);setForm({username:"",password:"",role:"sales",permissions:[]});await load()}catch(e){setError(e.response?.data?.message||"Unable to update permissions.")}finally{setSaving(false)}};
 const togglePermission=(permission)=>setForm(v=>({...v,permissions:v.permissions.includes(permission)?v.permissions.filter(x=>x!==permission):[...v.permissions,permission]}));
 const applyRole=role=>setForm(v=>({...v,role,permissions:rolePermissions[role]||[]}));
 if(!canManage && admin?.role!=="owner" && admin?.role!=="super_admin") return <div><h1 className="text-2xl font-black">Staff & Permissions</h1><p className="mt-2 text-slate-500">You can view staff accounts, but you do not have permission to manage them.</p></div>;
 return <div className="mx-auto max-w-7xl">
  <div className="mb-6"><h1 className="text-3xl font-black">Staff & Permissions</h1><p className="mt-1 text-sm text-slate-500">Manage staff accounts and fine-grained access to the new store modules.</p></div>
  {error&&<div className="mb-4 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700">{error}</div>}
  <form onSubmit={create} className="card mb-6 p-5"><h2 className="font-black">Create staff</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" required minLength="3" placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input className="input" required minLength="8" type="password" placeholder="Temporary password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select className="input" value={form.role} onChange={e=>applyRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{labels[r]||r}</option>)}</select><button disabled={saving} className="btn-yellow">{saving?"Creating...":"Create Staff"}</button></div><p className="mt-3 text-xs text-slate-500">New staff receive the selected role permissions. You can fine-tune them after creation.</p></form>
  <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Username</th><th>Role</th><th>Permissions</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td className="p-4" colSpan="6">Loading...</td></tr>:rows.map(row=><tr className="border-t" key={row.id}><td className="p-4 font-semibold">{row.username}</td><td>{labels[row.role]||row.role}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{row.permissions?.includes("*")?"All permissions":`${row.permissions?.length||0} permissions`}</span></td><td><span className={row.active?"text-emerald-600":"text-red-600"}>{row.active?"Active":"Inactive"}</span></td><td>{row.lastLoginAt?new Date(row.lastLoginAt).toLocaleString():"Never"}</td><td><div className="flex flex-wrap gap-2">{row.role!=="owner"&&<><button className="btn-soft" onClick={()=>startEdit(row)}>Permissions</button><button className="btn-soft" onClick={()=>toggle(row)}>{row.active?"Deactivate":"Activate"}</button></>}</div></td></tr>)}</tbody></table></div></div>
  {editing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4" onClick={()=>!saving&&setEditing(null)}><form className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-3xl bg-white p-5 sm:p-7" onClick={e=>e.stopPropagation()} onSubmit={saveEdit}><div className="flex items-start justify-between"><div><h2 className="text-2xl font-black">Edit Staff Permissions</h2><p className="text-sm text-slate-500">{form.username}</p></div><button type="button" className="btn-soft" onClick={()=>setEditing(null)}>Close</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Role<select className="input mt-1" value={form.role} onChange={e=>applyRole(e.target.value)}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label className="text-sm font-bold">Reset password (optional)<input className="input mt-1" minLength="8" type="password" value={form.password} onChange={e=>setForm(v=>({...v,password:e.target.value}))}/></label></div><div className="mt-5 grid gap-4 md:grid-cols-2">{Object.entries(groups).map(([group,permissions])=><section key={group} className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{group}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{permissions.map(permission=><label key={permission} className="flex items-center gap-2 rounded-xl bg-white p-2 text-xs font-semibold"><input type="checkbox" checked={form.permissions.includes(permission)||form.permissions.includes("*")} disabled={form.permissions.includes("*")} onChange={()=>togglePermission(permission)}/><span>{permission}</span></label>)}</div></section>)}</div><button className="btn-primary mt-6" disabled={saving}>{saving?"Saving...":"Save permissions"}</button></form></div>}
 </div>
}
