import {useEffect,useState} from "react";
import {Search, Edit3, Power} from "lucide-react";
import api from "../../lib/api";
import { cachedGet } from "../../lib/cache";
import ConfirmModal from "../../components/ConfirmModal";

const empty={name:"",phone:"",email:"",address:"",gstNumber:"",notes:""};
export default function Suppliers(){
 const[data,setData]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[confirm,setConfirm]=useState(null);
 const load=async()=>{setLoading(true);try{const r=await cachedGet(api,`/suppliers?q=${encodeURIComponent(q)}`,{key:`suppliers:admin:${q}`,revalidate:true});setData(r.data||[])}finally{setLoading(false)}};useEffect(()=>{const t=setTimeout(load,150);return()=>clearTimeout(t)},[q]);
 const save=async e=>{e.preventDefault();if(!form.name.trim())return;setSaving(true);try{await (editing?api.put(`/suppliers/${editing}`,form):api.post("/suppliers",form));setForm(empty);setEditing(null);await load()}finally{setSaving(false)}};
 const start=x=>{setEditing(x._id);setForm({name:x.name||"",phone:x.phone||"",email:x.email||"",address:x.address||"",gstNumber:x.gstNumber||"",notes:x.notes||""})};
 const deactivate=async id=>{try{await api.delete(`/suppliers/${id}`);setConfirm(null);await load()}catch(e){setConfirm({title:"Cannot deactivate",message:e.response?.data?.message||"Supplier has related records."})}};
 return <div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-black">Suppliers</h1><p className="mt-1 text-sm text-slate-500">Manage vendor contacts, GST details and purchase relationships.</p></div></div>
 <form onSubmit={save} className="card mt-6 p-5"><h2 className="font-black">{editing?"Edit supplier":"Add supplier"}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><input className="input" required placeholder="Supplier name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" placeholder="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="input" placeholder="GST Number" value={form.gstNumber} onChange={e=>setForm({...form,gstNumber:e.target.value})}/><input className="input lg:col-span-2" placeholder="Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><textarea className="input sm:col-span-2 lg:col-span-3" placeholder="Notes: payment terms, delivery lead time, return policy..." value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="mt-4 flex gap-2"><button disabled={saving} className="btn-primary">{saving?"Saving...":editing?"Update Supplier":"Add Supplier"}</button>{editing&&<button type="button" className="btn-soft" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form>
 <div className="card mt-6 overflow-hidden"><div className="border-b p-4"><div className="relative"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-10" placeholder="Search supplier, phone or email" value={q} onChange={e=>setQ(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Supplier</th><th>Contact</th><th>GST</th><th>Address</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td className="p-6" colSpan="6">Loading...</td></tr>:data.map(x=><tr className="border-t" key={x._id}><td className="p-4"><b>{x.name}</b>{x.notes&&<div className="mt-1 max-w-xs text-xs text-slate-400">{x.notes}</div>}</td><td>{x.phone||"—"}<div className="text-xs text-slate-500">{x.email||"—"}</div></td><td>{x.gstNumber||"—"}</td><td className="max-w-xs text-slate-500">{x.address||"—"}</td><td>{x.active?<span className="text-emerald-600">Active</span>:<span className="text-red-600">Inactive</span>}</td><td><div className="flex gap-2"><button className="btn-soft" onClick={()=>start(x)}><Edit3 size={15}/> Edit</button>{x.active&&<button className="btn-soft text-red-600" onClick={()=>setConfirm(x)}><Power size={15}/> Deactivate</button>}</div></td></tr>)}</tbody></table></div>{!loading&&!data.length&&<div className="p-10 text-center text-slate-400">No suppliers found.</div>}</div>
 <ConfirmModal open={Boolean(confirm)} title={confirm?.title||"Deactivate supplier?"} message={confirm?.message||`Deactivate ${confirm?.name}? Purchase history will be preserved.`} confirmText="Deactivate" danger onConfirm={()=>confirm?._id&&deactivate(confirm._id)} onClose={()=>setConfirm(null)}/>
 </div>
}
